# -*- coding: utf-8 -*-
"""Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

import pandas as pd
import numpy as np
import random
from datetime import datetime, timedelta

np.random.seed(42)
random.seed(42)

num_records = 50000

transaction_ids = [f"TXN{str(i).zfill(6)}" for i in range(1, num_records + 1)]

customer_ids = [f"CUST{random.randint(1000, 9999)}" for _ in range(num_records)]

amounts = np.random.exponential(scale=50, size=num_records).round(2)

transaction_types = ["Online", "ATM", "POS"]
transaction_type = [random.choice(transaction_types) for _ in range(num_records)]

start_date = datetime.now() - timedelta(days=365)
timestamps = [start_date + timedelta(days=random.randint(0, 365), hours=random.randint(0, 23), minutes=random.randint(0, 59)) for _ in range(num_records)]

locations = ["New York", "Los Angeles", "San Francisco", "Chicago", "Miami", "Houston", "Seattle", "Boston", "Denver", "Atlanta"]
transaction_locations = [random.choice(locations) for _ in range(num_records)]

card_types = ["Credit", "Debit"]
card_type = [random.choice(card_types) for _ in range(num_records)]

merchant_categories = ["Groceries", "Electronics", "Travel", "Fashion", "Restaurants", "Automotive", "Entertainment"]
merchant_category = [random.choice(merchant_categories) for _ in range(num_records)]

is_fraud = np.random.choice([0, 1], size=num_records, p=[0.99, 0.01])

df = pd.DataFrame({
    "TransactionID": transaction_ids,
    "CustomerID": customer_ids,
    "Amount": amounts,
    "TransactionType": transaction_type,
    "TimeOfTransaction": timestamps,
    "Location": transaction_locations,
    "CardType": card_type,
    "MerchantCategory": merchant_category,
    "IsFraud": is_fraud
})

df.to_csv("synthetic_fraud_dataset.csv", index=False)
print("Dataset generated successfully and saved as 'synthetic_fraud_dataset.csv'.")